apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  name: {{ include "keycloak.fullname" . }}-discovery
spec:
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
  clusterIP: None
  type: ClusterIP
