{{- if and .Values.components.spire.enabled (not .Values.openshift) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: spire-tornjak-api
  namespace: {{ .Values.spire.namespace }}
  labels:
    app: spire-tornjak-api
    {{- include "kagenti.labels" . | nindent 4 }}
    app.kubernetes.io/component: spire-tornjak-api
spec:
  parentRefs:
    - name: http
      namespace: kagenti-system
  hostnames:
    - "spire-tornjak-api.localtest.me"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: spire-tornjak-backend
          port: 10000
{{- end }}
