apiVersion: v1
kind: ServiceAccount
metadata:
  name: kagenti-ui-service-account
  namespace: kagenti-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kagenti-ui-fixed
  namespace: kagenti-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kagenti-ui-fixed
  template:
    metadata:
      labels:
        app: kagenti-ui-fixed
    spec:
      serviceAccountName: kagenti-ui-service-account
      containers:
        - name: kagenti-ui-container
          image: quay.io/shanand/kagenti-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi  

---
apiVersion: v1
kind: Service
metadata:
  name: kagenti-ui-fixed
  namespace: kagenti-system
spec:
  selector:
    app: kagenti-ui-fixed
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kagenti-ui-fixed
  namespace: kagenti-system
  labels:
    app: kagenti-ui-fixed
spec:
  parentRefs:
    - name: http
      namespace: kagenti-system
  hostnames:
    - "kagenti-ui-fixed.localtest.me"
  rules:
    - backendRefs:
        - name: kagenti-ui-fixed
          port: 8501 
