apiVersion: v2
name: kagenti-deps
description: A Helm chart for deploying the kagenti dependencies
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: gateway-api
    version: "~1.3.0"
    repository: "file://../gateway-api"
    condition: components.gatewayApi.enabled

  # Kubernetes-specific dependencies (community charts)
  - name: keycloak
    version: "*"
    repository: oci://registry-1.docker.io/bitnamicharts/keycloak
    condition: components.keycloak.enabled
    tags:
      - kubernetes

  - name: cert-manager
    version: "~1.19.0"
    # repository: "https://charts.jetstack.io"
    repository: oci://quay.io/jetstack/charts
    condition: components.certManager.enabled
    tags:
      - kubernetes

  - name: base # istio-base
    version: "~1.27.1"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: components.istio.enabled
    tags:
      - kubernetes

  - name: istiod
    version: "~1.27.1"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: components.istio.enabled
    tags:
      - kubernetes

  - name: cni # istio-cni
    version: "~1.27.1"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: components.istio.enabled
    tags:
      - kubernetes

  - name: kiali-server
    version: "~2.15.0"
    repository: "https://kiali.org/helm-charts"
    condition: components.kiali.enabled
    tags:
      - kubernetes

  - name: tekton-pipelines
    version: "~0.1.0"
    repository: "file://../tekton-pipelines"
    condition: components.tekton.enabled
    tags:
      - kubernetes

  - name: spire
    version: "~0.24.0"
    repository: "https://spiffe.github.io/helm-charts-hardened"
    condition: components.spire.enabled
    tags:
      - kubernetes

  - name: ingress-nginx
    version: "*"
    repository: https://kubernetes.github.io/ingress-nginx
    tags:
      - kubernetes
