# Global settings
openshift: true

tags:
  kubernetes: false

# ------------------------------------------------------------------
#  Control Panel: Enable or disable components here
# ------------------------------------------------------------------
components:
  agentNamespaces:
    enabled: true
  mcpInspector:
    enabled: true
  istio:
    enabled: true
  kiali:
    enabled: true  
  keycloak:
    enabled: true
  metricsServer:
    enabled: false
  otel:
    enabled: true
  registry:
    enabled: false
  spire:
    enabled: false
  tekton:
    enabled: true
  certManager:
    enabled: true  
  gatewayApi:  
    enabled: true
  ingressGateway:
    enabled: false 
  toolhive:
    enabled: true


common:
  kubectlImage: "quay.io/kubestellar/kubectl:1.30.14"

# ------------------------------------------------------------------
#  Components Configurations
# ------------------------------------------------------------------


# ------------------------------------------------------------------
#  Keycloak Configuration
# ------------------------------------------------------------------
keycloak:
  namespace: keycloak
  auth:
    adminUser: keycloakadmin
    adminPassword: your-secret-password


# ------------------------------------------------------------------
#  Istio Configuration
# ------------------------------------------------------------------
istio:
  communityCharts:
    enabled: false
  namespace: "istio-system"
  gatewayApiVersion: "v1.1.0"
  cni:
    profile: ambient
    namespace: istio-system
  ztunnel:
    namespace: istio-system  
  base: {}
  istiod: 
    profile: ambient
    namespace: istio-system 
  ingressGateway:
    name: istio-ingressgateway
    namespace: istio-system
    selector: ingressgateway
    

httpGateway:
  name: 
  namespace: "kagenti-system"
  

# ------------------------------------------------------------------
#  Cert Manager Configuration
# ------------------------------------------------------------------
certManager:
  namespace: cert-manager-operator

cert-manager:
  installCRDs: true
  namespace: cert-manager-operator

# ------------------------------------------------------------------
#  Spire Configuration
# ------------------------------------------------------------------
spire:
  namespace: zero-trust-workload-identity-manager
