apiVersion: v2
name: spire
description: Custom spire helm chart for Kagenti on vanilla Kubernetes clusters

type: application
version: 0.1.0
appVersion: "1.13.0"

dependencies:
  - name: spire-crds
    version: "~0.5.0"
    repository: "https://spiffe.github.io/helm-charts-hardened"
    condition: components.spire.enabled

  - name: spire
    version: "~0.27.0"
    repository: "https://spiffe.github.io/helm-charts-hardened"
    condition: components.spire.enabled
