apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{ include "keycloak.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
  selector:
    {{ include "keycloak.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-discovery
  labels:
    {{ include "keycloak.labels" . | nindent 4 }}
spec:
  selector:
    {{ include "keycloak.selectorLabels" . | nindent 4 }}
  clusterIP: None
  type: ClusterIP
